[2024-11-27T11:05:01.389+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/test_dag.py
[2024-11-27T11:05:01.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-27T11:05:01.400+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:05:01.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-27T11:05:01.441+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:05:01.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootsttrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2024-11-27T11:05:01.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-27T11:05:01.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.141 seconds
[2024-11-27T11:05:31.932+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/test_dag.py
[2024-11-27T11:05:31.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-27T11:05:31.938+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:05:31.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-27T11:05:31.948+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:05:31.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2024-11-27T11:05:31.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-27T11:05:32.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.101 seconds
[2024-11-27T11:06:02.358+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/test_dag.py
[2024-11-27T11:06:02.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-27T11:06:02.375+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:06:02.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-27T11:06:02.399+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:06:02.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2024-11-27T11:06:02.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-27T11:06:02.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.132 seconds
[2024-11-27T11:06:32.866+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/test_dag.py
[2024-11-27T11:06:32.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-27T11:06:32.873+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:06:32.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-27T11:06:32.883+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:06:32.881+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2024-11-27T11:06:32.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-27T11:06:33.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.202 seconds
[2024-11-27T11:07:03.470+0000] {processor.py:186} INFO - Started process (PID=101) to work on /opt/airflow/dags/test_dag.py
[2024-11-27T11:07:03.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-27T11:07:03.504+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:07:03.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-27T11:07:03.609+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:07:03.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2024-11-27T11:07:03.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-27T11:07:03.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.341 seconds
[2024-11-27T11:07:33.988+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/test_dag.py
[2024-11-27T11:07:33.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-27T11:07:33.996+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:07:33.995+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-27T11:07:34.008+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:07:34.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2024-11-27T11:07:34.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-27T11:07:34.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.093 seconds
[2024-11-27T11:08:04.789+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/test_dag.py
[2024-11-27T11:08:04.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-27T11:08:04.800+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:08:04.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-27T11:08:04.812+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:08:04.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2024-11-27T11:08:04.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-27T11:08:04.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2024-11-27T11:08:35.151+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/test_dag.py
[2024-11-27T11:08:35.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-11-27T11:08:35.162+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:08:35.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-11-27T11:08:35.182+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:08:35.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2024-11-27T11:08:35.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-11-27T11:08:35.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.082 seconds
