[2024-11-27T11:05:01.412+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:05:01.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py for tasks to queue
[2024-11-27T11:05:01.427+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:05:01.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:05:01.448+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:05:01.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-11-27T11:05:01.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:05:01.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py took 0.125 seconds
[2024-11-27T11:05:31.941+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:05:31.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py for tasks to queue
[2024-11-27T11:05:31.946+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:05:31.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:05:31.957+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:05:31.955+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-11-27T11:05:31.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:05:32.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py took 0.105 seconds
[2024-11-27T11:06:02.382+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:06:02.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py for tasks to queue
[2024-11-27T11:06:02.393+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:06:02.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:06:02.422+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:06:02.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-11-27T11:06:02.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:06:02.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py took 0.119 seconds
[2024-11-27T11:06:32.886+0000] {processor.py:186} INFO - Started process (PID=94) to work on /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:06:32.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py for tasks to queue
[2024-11-27T11:06:32.893+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:06:32.893+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:06:32.907+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:06:32.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-11-27T11:06:32.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:06:33.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py took 0.186 seconds
[2024-11-27T11:07:03.510+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:07:03.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py for tasks to queue
[2024-11-27T11:07:03.538+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:07:03.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:07:03.649+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:07:03.595+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-11-27T11:07:03.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:07:04.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py took 0.556 seconds
[2024-11-27T11:07:35.030+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:07:35.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py for tasks to queue
[2024-11-27T11:07:35.037+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:07:35.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:07:35.047+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:07:35.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-11-27T11:07:35.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:07:35.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py took 0.098 seconds
[2024-11-27T11:08:05.833+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:08:05.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py for tasks to queue
[2024-11-27T11:08:05.839+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:08:05.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:08:05.847+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:08:05.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-11-27T11:08:05.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:08:05.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py took 0.072 seconds
[2024-11-27T11:08:36.416+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:08:36.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py for tasks to queue
[2024-11-27T11:08:36.445+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:08:36.444+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:08:36.498+0000] {logging_mixin.py:190} INFO - [2024-11-27T11:08:36.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-11-27T11:08:36.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py
[2024-11-27T11:08:36.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt/caspar_health_dbt_cosmos/tests/dags/test_dag_example.py took 0.350 seconds
